//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_payroll_management_system.DbFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int Id { get; set; }
        public string userID { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string email_id { get; set; }
        public string designation { get; set; }
    }
}
